# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: build
on: [push, pull_request]

env:
  PYTHON_SRC_DIR: nextflow/vcf_prepper
  RUST_SRC_DIR: nextflow/vcf_prepper/src/rust/ensembl
  BIN_DIR: nextflow/vcf_prepper/bin

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install/Update Dependencies
        run: python3 -m pip install --upgrade build
      - name: Build
        run: python3 -m build ${{ PYTHON_SRC_DIR }}

  rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [
          bed_to_wig,
          merge_bed
          vcf_to_bed
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ matrix.BUILD_TARGET }}
        run: cargo build --manifest_file ${{ RUST_SRC_DIR }}/${{ matrix.BUILD_TARGET }}/Cargo.toml --artifact-dir ${{ BIN_DIR }}