name: nf-test
on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nf-core/setup-nextflow@v1
      - name: setup
        run: curl -fsSL https://code.askimed.com/install/nf-test | bash
      - name: test
        working-directory: nextflow/vcf_prepper
        run: ${GITHUB_WORKSPACE}/nf-test test tests
