name: nf-test
on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: curl -fsSL https://code.askimed.com/install/nf-test | bash
      - name: test
        run: ${GITHUB_WORKSPACE}/nf-test test nextflow/vcf_prepper/tests
