# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


name: unit-test
on: [pull_request]

# relative to job working directory ${{ GITHUB_WORKSPACE }}/nextflow/vcf_prepper
env:
  ENSEMBL_ROOT_DIR: repos

jobs:
  vcf_prepper:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: nextflow/vcf_prepper
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Ensembl/ensembl-vep
          ref: main
          path: 'nextflow/vcf_prepper/repos/ensembl-vep'
      - uses: actions/checkout@v4
        with:
          repository: Ensembl/ensembl
          ref: main
          path: 'nextflow/vcf_prepper/repos/ensembl'
      - uses: actions/checkout@v4
        with:
          repository: Ensembl/ensembl-variation
          ref: main
          path: 'nextflow/vcf_prepper/repos/ensembl-variation'
      - uses: actions/checkout@v4
        with:
          repository: Ensembl/VEP_plugins
          ref: main
          path: 'nextflow/vcf_prepper/repos/VEP_plugins'
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: nf-core/setup-nextflow@v1
        with:
          version: '24.04.3'

      - name: wait for MySQL
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P3306 --silent; do
            sleep 1
          done

      - name: load databases
        run: |
          mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE ensembl_genome_metadata;'
          mysql -h 127.0.0.1 -u root ensembl_genome_metadata < tests/testdata/ensembl_genome_metadata.dump
          mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE homo_sapiens_core_110_38;'
          mysql -h 127.0.0.1 -u root homo_sapiens_core_110_38 < tests/testdata/homo_sapiens_core_110_38.dump

      - name: setup htslib and bcftools
        run: |
          HTSLIB_VERSION=1.19
          BCFTOOLS_VERSION=1.19

          # install pre-requisites
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            zlib1g-dev \
            libbz2-dev \
            liblzma-dev \
            libcurl4-openssl-dev \
            libssl-dev
          
          # download
          wget -q https://github.com/samtools/htslib/releases/download/${HTSLIB_VERSION}/htslib-${HTSLIB_VERSION}.tar.bz2
          tar -xjf htslib-${HTSLIB_VERSION}.tar.bz2
          cd htslib-${HTSLIB_VERSION}
          
          # install
          ./configure --prefix=/usr/local
          make -j$(nproc)
          sudo make install

          # install bcftools
          wget https://github.com/samtools/bcftools/releases/download/${BCFTOOLS_VERSION}/bcftools-${BCFTOOLS_VERSION}.tar.bz2
          tar -xjf bcftools-${BCFTOOLS_VERSION}.tar.bz2
          cd bcftools-${BCFTOOLS_VERSION}

          ./configure --prefix=/usr/local
          make -j$(nproc)
          sudo make install

          # add to path
          echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV

      - name: setup nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: setup Python dependencies
        run: |
          python3 -m pip install ${GITHUB_WORKSPACE}/src/python
          python3 -m pip install -r requirements.txt

      - name: setup Perl dependencies
        run: |
          BIOPERL_VERSION=release-1-6-924
          HTSLIB_VERSION=1.19
          BIOHTS_VERSION=2.11
          LIB_DIR=${GITHUB_WORKSPACE}/nextflow/vcf_prepper/repos/ensembl-vep/modules/

          # add module path to PERL5LIB
          for lib_path in ${GITHUB_WORKSPACE}/nextflow/vcf_prepper/repos/ensembl*/modules 
          do
            PERL5LIB=${lib_path}:$PERL5LIB
          done
          export PERL5LIB

          # install Module::Build - needed for Bio::DB::HTS
          sudo apt-get update
          sudo apt-get install -y cpanminus
          cpanm Module::Build

          # install Bioperl - needed for Bio::DB::HTS
          wget https://github.com/bioperl/bioperl-live/archive/$BIOPERL_VERSION.zip
          unzip $BIOPERL_VERSION.zip
          rsync -r bioperl-live-$BIOPERL_VERSION/Bio ${LIB_DIR}/

          # install Bio::DB::HTS
          wget https://github.com/Ensembl/Bio-DB-HTS/archive/$BIOHTS_VERSION.zip
          unzip $BIOHTS_VERSION.zip
          cd Bio-DB-HTS-$BIOHTS_VERSION
          perl Build.PL --htslib ${GITHUB_WORKSPACE}/nextflow/vcf_prepper/htslib-${HTSLIB_VERSION}
          ./Build
          rsync -r lib/Bio ${LIB_DIR}/
          rsync blib/arch/auto/Bio/DB/HTS/Faidx/Faidx.so ${LIB_DIR}/

          # add PERL5LIB to env variable
          echo "PERL5LIB=$PERL5LIB" >> $GITHUB_ENV

      - name: test
        run: |
          export FTP_NFS_DIR=${GITHUB_WORKSPACE}/nextflow/vcf_prepper/tests/testdata
          export OLD_FTP_NFS_DIR=${GITHUB_WORKSPACE}/nextflow/vcf_prepper/tests/testdata
          
          sed -i -e 's|\${BASE_DIR}|'"$GITHUB_WORKSPACE"'|' ${GITHUB_WORKSPACE}/nextflow/vcf_prepper/tests/testdata/input_config.json
          nf-test test tests modules --ci --profile github
