# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


name: unit-test
on: [push, pull_request]

env:
  PYTHON_SRC_DIR: src/python/ensembl
  FTP_NFS_DIR:
  OLD_FTP_NFS_DIR:

jobs:
  vcf_prepper:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: nextflow/vcf_prepper
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Ensembl/ensembl-vep
          ref: main
          path: './repos/ensembl-vep'
      - uses: actions/checkout@v4
        with:
          repository: Ensembl/ensembl-variation
          ref: main
          path: './repos/ensembl-variation'
      - uses: actions/checkout@v4
        with:
          repository: Ensembl/VEP_plugins
          ref: main
          path: './repos/VEP_plugins'
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: nf-core/setup-nextflow@v1
        with:
          version: '24.04.3'

      - name: setup
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/
          python3 -m build ${{ PYTHON_SRC_DIR }}
          python3 -m pip install -r requirements.txt

      - name: test
        run: nf-test test tests --ci --profile github
